"""create runs, steps, bugs, artifacts tables

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-01 00:00:00

Hand-written to match `storage.models` exactly (rather than
autogenerated), since this is the first migration and there's no prior
schema for Alembic to diff against. Every subsequent migration should be
generated via `alembic revision --autogenerate` against a live DB running
this one, so drift between `models.py` and the migration history gets
caught automatically going forward.
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "runs",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("story_id", sa.String(36), nullable=True),
        sa.Column("test_plan_id", sa.String(36), nullable=True),
        sa.Column("target_url", sa.String(2048), nullable=True),
        sa.Column("state", sa.String(32), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_runs_story_id", "runs", ["story_id"])
    op.create_index("ix_runs_state", "runs", ["state"])
    op.create_index("ix_runs_created_at", "runs", ["created_at"])
    op.create_index("ix_runs_state_created_at", "runs", ["state", "created_at"])

    op.create_table(
        "steps",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("run_id", sa.String(36), sa.ForeignKey("runs.id", ondelete="CASCADE"), nullable=False),
        sa.Column("step_order", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(32), nullable=False),
        sa.Column("target_description", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column("resolution_strategy", sa.String(32), nullable=True),
        sa.Column("resolution_confidence", sa.Float(), nullable=True),
    )
    op.create_index("ix_steps_run_id", "steps", ["run_id"])
    op.create_index("ix_steps_run_order", "steps", ["run_id", "step_order"], unique=True)

    op.create_table(
        "bugs",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("run_id", sa.String(36), sa.ForeignKey("runs.id", ondelete="CASCADE"), nullable=False),
        sa.Column("title", sa.String(200), nullable=False),
        sa.Column("severity", sa.String(16), nullable=False),
        sa.Column("category", sa.String(32), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("expected_behavior", sa.Text(), nullable=False),
        sa.Column("actual_behavior", sa.Text(), nullable=False),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column("cluster_id", sa.String(36), nullable=True),
        sa.Column("occurrence_count", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("tracker_name", sa.String(32), nullable=True),
        sa.Column("tracker_ref", sa.String(64), nullable=True),
        sa.Column("tracker_url", sa.String(2048), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("filed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_bugs_run_id", "bugs", ["run_id"])
    op.create_index("ix_bugs_severity", "bugs", ["severity"])
    op.create_index("ix_bugs_category", "bugs", ["category"])
    op.create_index("ix_bugs_cluster_id", "bugs", ["cluster_id"])

    op.create_table(
        "artifacts",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("run_id", sa.String(36), sa.ForeignKey("runs.id", ondelete="CASCADE"), nullable=False),
        sa.Column("type", sa.String(32), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("path_or_url", sa.Text(), nullable=False),
        sa.Column("is_uploaded", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_artifacts_run_id", "artifacts", ["run_id"])


def downgrade() -> None:
    op.drop_table("artifacts")
    op.drop_table("bugs")
    op.drop_table("steps")
    op.drop_table("runs")